# Generated by Django 3.0.7 on 2020-08-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
