# Generated by Django 3.0.7 on 2020-08-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sellerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sellerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SellerAccount'),
        ),
    ]
