# Generated by Django 3.0.7 on 2020-08-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200810_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SellerAccount',
        ),
    ]
