# Generated by Django 3.0.7 on 2020-08-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_selleraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SellerAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SellerAccount'),
        ),
    ]
