# Generated by Django 3.0.7 on 2020-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200810_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sellerId',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
