# Generated by Django 3.0.7 on 2020-08-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200810_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='sellerorder',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
