# Generated by Django 3.0.7 on 2020-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200810_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sellerId',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
